FLAGS=-y -t tester --harness opencode --harness-auth none

test.multi-agent-collaboration-tests:
	scion start test-runner $(FLAGS) "You are the test-runner scion agent, do NOT delete yourself. Read .design/scion-localhost-workflows.md and test/multi-agent-collaboration-tests.md then run the tests. Do not touch the server, just run the tests."