[registry."host.bridge.internal:5000"]
  http = true
  insecure = true
[registry."localhost:5000"]
  http = true
  insecure = true
[registry."host.docker.internal:5000"]
  http = true
  insecure = true

